export type Locale = 'en' | 'es'

export const EDITOR_LANGUAGE_STORAGE_KEY = 'fluentreport-editor-locale'

export const LOCALE_OPTIONS: Array<{ value: Locale; label: string }> = [
  { value: 'en', label: 'English' },
  { value: 'es', label: 'Espanol' },
]

export function isLocale(value: string): value is Locale {
  return value === 'en' || value === 'es'
}

export function getInitialLocale(): Locale {
  if (typeof window === 'undefined') {
    return 'en'
  }

  const stored = window.localStorage.getItem(EDITOR_LANGUAGE_STORAGE_KEY)
  if (stored && isLocale(stored)) {
    return stored
  }

  return window.navigator.language.toLowerCase().startsWith('es') ? 'es' : 'en'
}

export const EDITOR_COPY = {
  en: {
    appTitle: 'FluentReport Schema Studio',
    language: 'Language',
    untitledReport: 'untitled-report',
    pageStatus: (current: number, total: number) => `Page ${current} / ${total}`,
    pageLabel: (index: number) => `Page ${index}`,
    blocksStatus: (count: number) => `${count} blocks`,
    selectedStatus: (count: number) => `${count} selected`,
    noSelectionStatus: 'No selection',
    editorToolbarAria: 'Editor toolbar',
    contextToolbarAria: 'Context toolbar',
    document: 'Document',
    layers: 'Layers',
    metadata: 'Metadata',
    name: 'Name',
    title: 'Title',
    companyParam: 'Company param',
    periodParam: 'Period param',
    dataSources: 'Data sources',
    html: 'HTML',
    maxWidth: 'Max width',
    fontFamily: 'Font family',
    pageDivider: 'Page divider',
    outlook: 'Outlook',
    pageSummary: (pageIndex: number, blockCount: number, selectedCount: number) =>
      `Page ${pageIndex} · ${blockCount} blocks · ${selectedCount > 0 ? `${selectedCount} selected` : 'no selection'}`,
    page: 'Page',
    active: 'Active',
    newPage: 'New page',
    moveUp: 'Move up',
    moveDown: 'Move down',
    deletePage: 'Delete page',
    moveSelection: 'Move selection',
    noDestination: 'No destination',
    send: 'Send',
    insert: 'Insert',
    addText: 'Add text',
    addLine: 'Add line',
    addSpacer: 'Add spacer',
    addPageBreak: 'Add page break',
    addImage: 'Add image',
    addTable: 'Add table',
    addRepeat: 'Add repeat/list',
    zoom: 'Zoom',
    zoomOut: 'Zoom out',
    resetZoom: 'Reset zoom',
    zoomIn: 'Zoom in',
    rulers: 'Rulers',
    showYaml: 'Show YAML',
    hideYaml: 'Hide YAML',
    openInspector: 'Open inspector',
    inspector: 'Inspector',
    copyYaml: 'Copy YAML',
    copyYamlTitle: 'Copy YAML to clipboard',
    download: 'Download',
    downloadTitle: 'Download .frpt.yaml file',
    properties: 'Properties',
    close: 'Close',
    emptySelectionHint: 'Select one or more elements to see contextual actions, group them, or edit their quick properties.',
    mixedSelection: 'Mixed selection',
    groupLabel: (groupId: string) => `Group ${groupId}`,
    selection: 'Selection',
    duplicate: 'Duplicate',
    group: 'Group',
    ungroup: 'Ungroup',
    deleteSelection: 'Delete selection',
    pageTools: 'Page',
    leftMargin: 'Left margin',
    center: 'Center',
    rightMargin: 'Right margin',
    layout: 'Layout',
    alignLeft: 'Align left',
    centerX: 'Center X',
    alignRight: 'Align right',
    top: 'Top',
    centerY: 'Center Y',
    bottom: 'Bottom',
    distributeX: 'Distribute X',
    distributeY: 'Distribute Y',
    matchWidth: 'Match width',
    matchHeight: 'Match height',
    text: 'Text',
    textAlign: 'Text align',
    leftShort: 'Left',
    centerShort: 'Center',
    rightShort: 'Right',
    justifyShort: 'Justify',
    size: 'Size',
    styleRef: 'StyleRef',
    color: 'Color',
    bold: 'Bold',
    italic: 'Italic',
    line: 'Line',
    thickness: 'Thickness',
    spacer: 'Spacer',
    image: 'Image',
    upload: 'Upload',
    imageFit: 'Image fit',
    contain: 'Contain',
    cover: 'Cover',
    none: 'None',
    source: 'Source',
    sourcePlaceholder: 'Path or URL',
    table: 'Table',
    repeat: 'Repeat',
    growth: 'Growth',
    overflow: 'Overflow',
    growDown: 'Grow down',
    fixedFrame: 'Fixed frame',
    fixed: 'Fixed',
    nextPage: 'Next page',
    truncate: 'Truncate',
    keepTogether: 'Keep together',
    keepTogetherBeforeBreak: 'Keep together before breaking',
    columns: 'Columns',
    columnsCount: (count: number) => `${count} cols`,
    frame: 'Frame',
    width: 'Width',
    height: 'Height',
    content: 'Content',
    typography: 'Typography',
    appearance: 'Appearance',
    spacing: 'Spacing',
    dataSource: 'Data source',
    fit: 'Fit',
    alt: 'Alt',
    tableName: 'Name',
    repeatName: 'Name',
    template: 'Template',
    gap: 'Gap',
    actions: 'Actions',
    moveLayerUp: 'Move up',
    moveLayerDown: 'Move down',
    noSelectionInspector: 'Nothing selected',
    unconfiguredBlock: 'Block without settings',
    loadImage: 'Upload image',
    tableColumnsHelp: 'One column per line: field | header | width | align',
    growthHelp: 'Classic report-editor behavior: grow downward, continue on the next page, or truncate, with an option to keep the block together.',
    imagePlaceholder: 'Image placeholder',
    selectedImageAlt: 'Selected image',
    emptyTextBlock: 'Empty text block',
    spacerSummary: (size: number) => `${size}px spacer`,
    emptyImageBlock: 'Empty image block',
    forceNewPage: 'Forces a new page',
    pageBreak: 'Page break',
    noSelectionMixed: 'No selection',
    blockTypes: {
      text: 'Text',
      line: 'Line',
      spacer: 'Spacer',
      image: 'Image',
      table: 'Table',
      repeat: 'Repeat',
      pageBreak: 'Page break',
    },
  },
  es: {
    appTitle: 'FluentReport Schema Studio',
    language: 'Idioma',
    untitledReport: 'reporte-sin-titulo',
    pageStatus: (current: number, total: number) => `Pagina ${current} / ${total}`,
    pageLabel: (index: number) => `Pagina ${index}`,
    blocksStatus: (count: number) => `${count} bloques`,
    selectedStatus: (count: number) => `${count} seleccionado${count > 1 ? 's' : ''}`,
    noSelectionStatus: 'Sin seleccion',
    editorToolbarAria: 'Barra del editor',
    contextToolbarAria: 'Barra contextual',
    document: 'Documento',
    layers: 'Capas',
    metadata: 'Metadatos',
    name: 'Nombre',
    title: 'Titulo',
    companyParam: 'Param. empresa',
    periodParam: 'Param. periodo',
    dataSources: 'Fuentes de datos',
    html: 'HTML',
    maxWidth: 'Ancho maximo',
    fontFamily: 'Familia tipografica',
    pageDivider: 'Separador de pagina',
    outlook: 'Outlook',
    pageSummary: (pageIndex: number, blockCount: number, selectedCount: number) =>
      `Pagina ${pageIndex} · ${blockCount} bloques · ${selectedCount > 0 ? `${selectedCount} seleccionado${selectedCount > 1 ? 's' : ''}` : 'sin seleccion'}`,
    page: 'Pagina',
    active: 'Activa',
    newPage: 'Nueva pagina',
    moveUp: 'Subir',
    moveDown: 'Bajar',
    deletePage: 'Eliminar pagina',
    moveSelection: 'Mover seleccion',
    noDestination: 'Sin destino',
    send: 'Enviar',
    insert: 'Insertar',
    addText: 'Agregar texto',
    addLine: 'Agregar linea',
    addSpacer: 'Agregar espaciador',
    addPageBreak: 'Agregar salto de pagina',
    addImage: 'Agregar imagen',
    addTable: 'Agregar tabla',
    addRepeat: 'Agregar repetidor/lista',
    zoom: 'Zoom',
    zoomOut: 'Reducir zoom',
    resetZoom: 'Restablecer zoom',
    zoomIn: 'Aumentar zoom',
    rulers: 'Reglas',
    showYaml: 'Mostrar YAML',
    hideYaml: 'Ocultar YAML',
    openInspector: 'Abrir inspector',
    inspector: 'Inspector',
    copyYaml: 'Copiar YAML',
    copyYamlTitle: 'Copiar YAML al portapapeles',
    download: 'Descargar',
    downloadTitle: 'Descargar archivo .frpt.yaml',
    properties: 'Propiedades',
    close: 'Cerrar',
    emptySelectionHint: 'Selecciona uno o mas elementos para ver acciones contextuales, agruparlos o editar sus propiedades rapidas.',
    mixedSelection: 'Seleccion mixta',
    groupLabel: (groupId: string) => `Grupo ${groupId}`,
    selection: 'Seleccion',
    duplicate: 'Duplicar',
    group: 'Agrupar',
    ungroup: 'Desagrupar',
    deleteSelection: 'Eliminar seleccion',
    pageTools: 'Pagina',
    leftMargin: 'Margen izq.',
    center: 'Centrar',
    rightMargin: 'Margen der.',
    layout: 'Disposicion',
    alignLeft: 'Alinear izq.',
    centerX: 'Centrar X',
    alignRight: 'Alinear der.',
    top: 'Arriba',
    centerY: 'Centro Y',
    bottom: 'Abajo',
    distributeX: 'Distribuir X',
    distributeY: 'Distribuir Y',
    matchWidth: 'Igualar ancho',
    matchHeight: 'Igualar alto',
    text: 'Texto',
    textAlign: 'Alineacion de texto',
    leftShort: 'Izq.',
    centerShort: 'Centro',
    rightShort: 'Der.',
    justifyShort: 'Just.',
    size: 'Tamano',
    styleRef: 'Estilo ref.',
    color: 'Color',
    bold: 'Negrita',
    italic: 'Cursiva',
    line: 'Linea',
    thickness: 'Grosor',
    spacer: 'Espaciador',
    image: 'Imagen',
    upload: 'Cargar',
    imageFit: 'Ajuste de imagen',
    contain: 'Contener',
    cover: 'Cubrir',
    none: 'Ninguno',
    source: 'Fuente',
    sourcePlaceholder: 'Ruta o URL',
    table: 'Tabla',
    repeat: 'Repetidor',
    growth: 'Crecimiento',
    overflow: 'Desborde',
    growDown: 'Crecer hacia abajo',
    fixedFrame: 'Marco fijo',
    fixed: 'Fijo',
    nextPage: 'Pagina siguiente',
    truncate: 'Truncar',
    keepTogether: 'Mantener unido',
    keepTogetherBeforeBreak: 'Mantener unido antes de partir',
    columns: 'Columnas',
    columnsCount: (count: number) => `${count} columnas`,
    frame: 'Frame',
    width: 'Ancho',
    height: 'Alto',
    content: 'Contenido',
    typography: 'Tipografia',
    appearance: 'Apariencia',
    spacing: 'Espaciado',
    dataSource: 'Fuente de datos',
    fit: 'Ajuste',
    alt: 'Alt',
    tableName: 'Nombre',
    repeatName: 'Nombre',
    template: 'Plantilla',
    gap: 'Separacion',
    actions: 'Acciones',
    moveLayerUp: 'Subir',
    moveLayerDown: 'Bajar',
    noSelectionInspector: 'Nada seleccionado',
    unconfiguredBlock: 'Bloque sin ajustes',
    loadImage: 'Cargar imagen',
    tableColumnsHelp: 'Una columna por linea: field | header | width | align',
    growthHelp: 'Comportamiento tipo editor de reportes: crecer hacia abajo, continuar en la siguiente pagina o truncar, y opcionalmente mantener unido.',
    imagePlaceholder: 'Marcador de imagen',
    selectedImageAlt: 'Imagen seleccionada',
    emptyTextBlock: 'Bloque de texto vacio',
    spacerSummary: (size: number) => `Espaciador ${size}px`,
    emptyImageBlock: 'Bloque de imagen vacio',
    forceNewPage: 'Fuerza una nueva pagina',
    pageBreak: 'Salto de pagina',
    noSelectionMixed: 'Sin seleccion',
    blockTypes: {
      text: 'Texto',
      line: 'Linea',
      spacer: 'Espaciador',
      image: 'Imagen',
      table: 'Tabla',
      repeat: 'Repetidor',
      pageBreak: 'Salto de pagina',
    },
  },
} as const