name: Publish to NuGet

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'README.md'
      - 'LICENSE'

jobs:
  publish:
    name: Pack & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --no-restore --configuration Release

      - name: Pack FluentReport
        run: dotnet pack src/FluentReport/FluentReport.csproj --no-build --configuration Release --output ./nupkgs

      - name: Pack FluentReport.Excel
        run: dotnet pack src/FluentReport.Excel/FluentReport.Excel.csproj --no-build --configuration Release --output ./nupkgs

      - name: Pack FluentReport.Rdlc
        run: dotnet pack src/FluentReport.Rdlc/FluentReport.Rdlc.csproj --no-build --configuration Release --output ./nupkgs

      - name: Push to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_FLUENT_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
